add shell settings from nodejs buildpack

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,5 +1,12 @@
 #!/usr/bin/env bash
 
+set -e
+set -o pipefail   # don't ignore exit codes when piping output
+set -o nounset    # fail on unset variables
+unset GIT_DIR     # Avoid GIT_DIR leak from previous build steps
+
+type jq
+
 echo "Parsing VCAP_SERVICES"
 
 cd $BUILD_DIR
